### ISSUE TITLE
Contao 4.4 Managed Edition

### ISSUE THREAD

**Issue by stefanschleich** [1up-lab/contao-j2b#1]
Leider bekomme ich die Extension unter Contao 4.4.5 Managed Edition nicht zum laufen. Es tut sich einfach nichts. Ich habe die Extension über den Contao Manager installiert. Kann es sein, dass der Hook gar nicht greift? Wie könnte ich das prüfen?

**Comment by bytehead** [comment]
Die Extension ist momentan noch nicht kompatibel mit der Managed Edition von Contao. Es gibt da bereits Bemühungen, die Funktionalität über den Core abzubilden (https://github.com/contao/core-bundle/issues/1123).
Die Änderungen um die Extension kompatibel zu machen, wären relativ klein. Ich schiebe die nächsten Tage mal noch ein Update nach.

**Comment by stefanschleich** [comment]
Cool, vielen Dank. Wenn ich deinen Code richtig verstehe, laufen die Scripte nicht mehr durch den Combiner, sondern werden als einzelne Script-Tags ausgegeben. Ist das so? Und wenn ja, hast du vor das zu ändern?

**Comment by bytehead** [comment]
Die Scripte sind nie durch den Combiner gelaufen. Die Extension gibt einfach alle Javascripts, die ursprünglich  im `<head>` ausgegeben  werden, vor dem `</body>`-Tag aus.

**Comment by bytehead** [comment]
Die ganzen Flags werden auch explizit weggestrippt: 
`$javascript = preg_replace('/\|.*/', '', $javascript);`

**Comment by bytehead** [comment]
Kannst du mal versuchen, den `dev-feature/contao-4`-Branch in deiner ME zu installieren?

**Comment by stefanschleich** [comment]
Das hat funktioniert. Zumindest mit manuell zu TL_HEAD und TL_JAVASCRIPT hinzugefügten Inhalten. Bei von Contao hinzugefügten Einträgen sieht es anders aus:

Fall 1: Wenn ich im Seitenlayout jQuery lokal einbinde und dort zusätzlich ein jQuery Template  auswähle (z.B. j_accordion), wird erst das Template gerendert und dann jQuery geladen:

```html
<body>
...
<script src="assets/jquery-ui/js/jquery-ui.min.js"></script>
<script>
  jQuery(function($) {
    $(document).accordion({
      // Put custom options here
      ...
    });
  });
</script>
<script type="text/javascript" src="assets/jquery/js/jquery.min.js"></script>
<script type="text/javascript" src="files/theme/vendor/Web/files/theme/vendor/jsor/lity-2.3.0/dist/lity.min.js"></script>
</body>
```
👉 `Uncaught ReferenceError: jQuery is not defined`

Fall 2: Wenn ich im Seitenlayout jQuery nicht nur lokal einbinde, sondern per CDN mit lokalem Fallback, passiert folgendes:

```html
<head>
  ...
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
  <script>window.jQuery || document.write('<script src="assets/jquery/js/jquery.min.js">\x3C/script>')</script>
  ...
</head>
...
<body>
... 
<script src="assets/jquery-ui/js/jquery-ui.min.js"></script>
<script>
  jQuery(function($) {
    $(document).accordion({
      // Put custom options here
      ...
    });
  });
</script>
<script type="text/javascript" src="files/theme/vendor/Web/files/theme/vendor/jsor/lity-2.3.0/dist/lity.min.js"></script>
</body>
```

Siehst du eine Möglichkeit, darauf zu reagieren?

**Comment by bytehead** [comment]
Ja das ist mir beim testen auch aufgefallen. Leider habe ich auf die schnelle keine Lösung dafür gefunden.
Wir selber arbeiten mittlerweile mit z.T. mit Gulp, neuerdings mit Webpack und brauchen somit diese Extension gar nicht mehr 🙈
